### ISSUE TITLE
persist change in test template

### ISSUE THREAD

**Issue by boyangwang** [zalmoxisus/redux-devtools-test-generator#2]
Hi, the generator is a brilliant idea and I love using it.

There's one issue. When used in redux devtool chrome extension, there's no way to persist the change to template. When modify existing template (e.g. Mocha template), it's gone after refresh. And it's not possible to create new template (hitting "Add" doesn't do anything).

Can we fix in chrome extension? We can choose to fix one or more of the following:
1. make change to existing template permanent
2. make adding new template work
3. add 'import template' feature, if 2 is not possible

Would appreciate if you can point me to the right direction. I will create a PR

**Comment by zalmoxisus** [comment]
Thanks for the report! Could you provide steps to reproduce the problem? I just checked it and it seems to work:
![qhl2njnvme](https://cloud.githubusercontent.com/assets/7957859/19128768/73a04888-8b4d-11e6-9c9c-4b2c9a20d9a1.gif)

**Comment by zalmoxisus** [comment]
Anything about the extension UI can be found in [`remotedev-app`](https://github.com/zalmoxisus/remotedev-app), it's just a web app so it would be easy to contribute. What you need is:
- [the component](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/components/TestForm.js)
- [the reducer](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/reducers/test.js)
- [the persistor middleware](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/middlewares/persist.js).

**Comment by boyangwang** [comment]
Hi,
I managed to make it work. Previously I was invoking it from
Chrome Blink developer console -> Redux tab

Now I invoke it from
address bar  -> click Redux devtools icon

And it works fine. Thanks again
