### ISSUE TITLE
in generated tests, new state doesn't have 'null' or 'undefined' in it

### ISSUE THREAD

**Issue by boyangwang** [zalmoxisus/redux-devtools-test-generator#4]
In devtools, properties with value 'null' or 'undefined' are not rendered in state tab. Along the same line, properties with value 'null' or 'undefined' are not there in generated tests' expected state object. This later causes tests to fail in, say chai.expect:

`expect({bestScore: null}).to.deep.equal({}); // this fails!`

Ignoring them doesn't seem to be correct behavior

**Comment by zalmoxisus** [comment]
@boyangwang, are you sure about `null`? It should work, the problem is only with `undefined`, because `JSON.stringify({bestScore: undefined})` returns `{}`. I'm working on a way to send data without stringifying it.

**Comment by boyangwang** [comment]
@zalmoxisus you are right. It's for undefined only. So one work around is to give null as initial value to properties.

I tried to work around this by do a JSON.stringify before assertions, but this doesn't work as sequence of properties can change:

```
obj = {}; obj.name="X"; obj.os="linux";
JSON.stringify(obj);
obj = {}; obj.os="linux"; obj.name="X";
JSON.stringify(obj);
```

One working workaround is to JSON.stringify -> JSON.parse

I'm currently using this helper to remove `undefined`:

```
function cleanFalsy(obj) {
    for (let prop in obj) {
        if (obj[prop] === undefined)
            delete obj[prop];
        else
            obj[prop] = cleanFalsy(obj[prop]); 
    }
    return obj;
}
```

And this helper is added to my template. So it's not a blocking issue. Please make your judgement to decide if this should be fix/wontfix
Thanks for your all amazing work :)

**Comment by zalmoxisus** [comment]
@boyangwang, thanks for investigating this. We had a solution in https://github.com/zalmoxisus/redux-devtools-extension/issues/60, but it affects the performance a lot. Other workarounds will make the serialization slow as well (as you have to traverse the whole state). I'm working on an another approach to send data to the extension via shared workers without serializing it.

**Comment by zalmoxisus** [comment]
Hey @boyangwang,

Sorry, I forgot to write here. Now you can just set `serializeState` and `serializeAction` extension's parameters to `true`, and it will serialize  symbols, dates, regexes, undefined, error objects, and functions. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.4) for details.
